configuration:
  - Native
  - WSL

# Test against this version of Node.js
environment:
  matrix:
    - nodejs_version: "16"
    #- nodejs_version: "14"
    #- nodejs_version: "12"
    #- nodejs_version: "10"
    #- nodejs_version: "8"
    # - nodejs_version: "6"
    # - nodejs_version: "4"

image: Visual Studio 2022
matrix:
  fast_finish: false
  exclude:
    - configuration: Native
      nodejs_version: "16"
    - configuration: WSL
      nodejs_version: "8"
    - configuration: WSL
      nodejs_version: "6"
    - configuration: WSL
      nodejs_version: "4"

  allow_failures:
    - nodejs_version: "4" # for eslint 5

platform:
  - x86
  #- x64

# Initialization scripts. (runs before repo cloning)
init:
  # Declare version-numbers of packages to install
  - ps: >-
      if ($env:nodejs_version -eq "4") {
        $env:NPM_VERSION="3"
      }
      if ($env:nodejs_version -in @("8")) {
        $env:NPM_VERSION="6"
      }
      if ($env:nodejs_version -in @("10", "12", "14", "16")) {
        $env:NPM_VERSION="6" # TODO: use npm 7
        $env:NPM_CONFIG_LEGACY_PEER_DEPS="true"
      }
  - ps: >-
      $env:ESLINT_VERSION="7";
      if ([int]$env:nodejs_version -le 8) {
        $env:ESLINT_VERSION="6"
      }
      if ([int]$env:nodejs_version -le 7) {
        $env:ESLINT_VERSION="5"
      }
      if ([int]$env:nodejs_version -le 6) {
        $env:ESLINT_VERSION="4"
      }
  - ps: $env:WINDOWS_NYC_VERSION = "15.0.1"
  - ps: $env:TRAVIS_NODE_VERSION = $env:nodejs_version

  # Add `ci`-command to `PATH` for running commands either using cmd or wsl depending on the configuration
  - ps: $env:PATH += ";$(Join-Path $(pwd) "scripts")"

# Install scripts. (runs after repo cloning)
before_build:
  # Install propert `npm`-version
  - IF DEFINED NPM_VERSION ci sudo npm install -g npm@%NPM_VERSION%

  # Install dependencies
  - ci npm install
  - ci npm run copy-metafiles
  - bash ./tests/dep-time-travel.sh 2>&1

  # fix symlinks
  - git config core.symlinks true
  - git reset --hard
  - ci git reset --hard

  # Install dependencies of resolvers
  - ps: >-
      $resolverDir = "./resolvers";
      $resolvers = @();
      Get-ChildItem -Directory $resolverDir |
        ForEach {
          $resolvers += "$(Resolve-Path $(Join-Path $resolverDir $_))";
        }
      $env:RESOLVERS = [string]::Join(";", $resolvers);
  - FOR %%G in ("%RESOLVERS:;=";"%") do ( pushd %%~G & ci npm install & popd )

  # Install proper `eslint`-version
  - IF DEFINED ESLINT_VERSION ci npm install --no-save eslint@%ESLINT_VERSION%

# Build scripts (project isn't actually built)
build_script:
  - ps: "# This Project isn't actually built"

# Test scripts
test_script:
  # Output useful info for debugging.
  - ci node --version
  - ci npm --version

  # Run core tests
  - ci npm run pretest
  - ci npm run tests-only

  # Run resolver tests
  - ps: >-
      $resolverDir = "./resolvers";
      $resolvers = @();
      Get-ChildItem -Directory $resolverDir |
        ForEach {
          $resolvers += "$(Resolve-Path $(Join-Path $resolverDir $_))";
        }
      $env:RESOLVERS = [string]::Join(";", $resolvers);
  - FOR %%G in ("%RESOLVERS:;=";"%") do ( pushd %%~G & ci npm test & popd )

# Configuration-specific steps
for:
  - matrix:
      except:
        - configuration: WSL
    install:
      # Get the latest stable version of Node.js or io.js
      - ps: Install-Product node $env:nodejs_version
    before_test:
      # Upgrade nyc
      - ci npm i --no-save nyc@%WINDOWS_NYC_VERSION%
      - ps: >-
          $resolverDir = "./resolvers";
          $resolvers = @();
          Get-ChildItem -Directory $resolverDir |
            ForEach {
              Push-Location $(Resolve-Path $(Join-Path $resolverDir $_));
              ci npm ls nyc > $null;
              if ($?) {
                $resolvers += "$(pwd)";
              }
              Pop-Location;
            }
          $env:RESOLVERS = [string]::Join(";", $resolvers);
      - IF DEFINED RESOLVERS FOR %%G in ("%RESOLVERS:;=";"%") do ( pushd %%~G & ci npm install --no-save nyc@%WINDOWS_NYC_VERSION% & popd )
    # TODO: enable codecov for native windows builds
    #on_success:
    #- ci $ProgressPreference = 'SilentlyContinue'
    #- ci Invoke-WebRequest -Uri https://uploader.codecov.io/latest/windows/codecov.exe
    #- ci -Outfile codecov.exe
    #- ci .\codecov.exe
  - matrix:
      only:
        - configuration: WSL
    # Install scripts. (runs after repo cloning)
    environment:
      GIT_REDIRECT_STDERR: 2>&1

    install:
      # Get a specific version of Node.js
      - ps: $env:WSLENV += ":nodejs_version"
      - ps: wsl sudo apt-get purge --auto-remove nodejs
      - ps: wsl sudo apt-get purge --auto-remove npm
      #- ps: wsl sudo apt-get update
      #- ps: wsl sudo apt-get install build-essential libssl-dev
      # - wsl --list --verbose
      - wsl which -a bash
      - wsl printenv
      #- ps: $ErrorActionPreference = 'SilentlyContinue'
      - ps: $env:GIT_REDIRECT_STDERR = '2>&1'
      - ps: $env:WSLENV += ":GIT_REDIRECT_STDERR"
      #- ps: wsl curl --fail -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh `| sudo APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1 -E bash -
      - wsl curl -sL -o- https://raw.githubusercontent.com/AndyOGo/nvm/bugfix/powershell-git-clone-stderr/install.sh | bash -
      - wsl echo "DONE install"
      - wsl ls -aR $HOME
      # - wsl ls -ad /
      # - wsl ls -a /mnt/c/Users/appveyor/.nvm/
      - ps: $env:NVM_DIR="$HOME/.nvm"
      - ps: $env:WSLENV += ":NVM_DIR"
      - wsl echo "HOME=$HOME"
      - wsl echo "NVM_DIR=$NVM_DIR"
      - wsl echo "Load nvm"
      - wsl [ -s "$HOME/.nvm/nvm.sh" ] && sudo APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1 source "$HOME/.nvm/nvm.sh"  # This loads nvm
      #- ps: wsl echo '[ -s "$HOME/.nvm/nvm.sh" ] && source "$HOME/.nvm/nvm.sh"' `| sudo APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1 -E bash -  # This loads nvm
      #- wsl [ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh"  # This loads nvm
      #- ps: wsl sudo APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1 /home/appveyor/.nvm/nvm.sh install ${nodejs_version}
      #- ps: wsl sudo APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1 /home/appveyor/.nvm/nvm.sh use ${nodejs_version}
      - wsl nvm install ${nodejs_version}
      - wsl nvm use ${nodejs_version}
      #- wsl which -a nvm
      #- wsl which -a node
      #- wsl which -a npm

    on_success:
      - ci curl -Os https://uploader.codecov.io/latest/linux/codecov
      - ci chmod +x codecov
      - ci ./codecov

build: on
